// try {
//   let y = 1;
//   const x = 2;
//   y = 3;
// } catch (err) {
//   alert(err.message);
// }

try{  
    var a=2;  
    if(a==2)  
    console.log("ok");  
    }  
    catch(Error){  
    console.log("Error found"+e.message);  
    }  
    finally{  
     console.log("Value of a is 2 ");  
    }  